export const RuntimeActions = {
    GET_DATA: 'GET_DATA',
    GENERATE_SCENARIOS: 'GENERATE_SCENARIOS',
    EVALUATE_COVERAGE: 'EVALUATE_COVERAGE',
    SAVE_SCENARIOS: 'SAVE_SCENARIOS',
    GET_GEMINI_MODELS: 'GET_GEMINI_MODELS',
    GET_COPILOT_MODELS: 'GET_COPILOT_MODELS',
    GET_GROQ_MODELS: 'GET_GROQ_MODELS'
};